spring:
  application:
    name: servicio-seguridad
  cloud:
    config:
      uri: http://localhost:8081
      username: root
      password: s3cr3t
  boot:
    admin:
      client:
        url: http://localhost:8086

server:
  error:
    include-message: always